package com.multifitaundh.service;

import com.multifitaundh.dto.TestimonialDto;
import com.multifitaundh.dto.TrainerDto;
import com.multifitaundh.dto.TrialLeadDto;
import com.multifitaundh.exception.ResourceNotFoundException;
import com.multifitaundh.model.Testimonial;
import com.multifitaundh.model.Trainer;
import com.multifitaundh.model.TrialLead;
import com.multifitaundh.repository.TestimonialRepository;
import com.multifitaundh.repository.TrainerRepository;
import com.multifitaundh.repository.TrialLeadRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class ContentService {

    private final TrainerRepository trainerRepository;
    private final TestimonialRepository testimonialRepository;
    private final TrialLeadRepository trialLeadRepository;

    @Autowired
    public ContentService(TrainerRepository trainerRepository, TestimonialRepository testimonialRepository, TrialLeadRepository trialLeadRepository) {
        this.trainerRepository = trainerRepository;
        this.testimonialRepository = testimonialRepository;
        this.trialLeadRepository = trialLeadRepository;
    }

    public List<TrainerDto> getAllTrainers() {
        return trainerRepository.findAll().stream()
                .map(this::mapToTrainerDto)
                .collect(Collectors.toList());
    }

    public TrainerDto getTrainerById(UUID id) {
        Trainer trainer = trainerRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Trainer not found with id: " + id));
        return mapToTrainerDto(trainer);
    }

    public TrainerDto createTrainer(TrainerDto trainerDto) {
        Trainer trainer = mapToTrainerEntity(trainerDto);
        trainer.setId(null); // Ensure ID is generated by DB
        Trainer savedTrainer = trainerRepository.save(trainer);
        return mapToTrainerDto(savedTrainer);
    }

    public TrainerDto updateTrainer(UUID id, TrainerDto trainerDto) {
        Trainer existingTrainer = trainerRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Trainer not found with id: " + id));

        existingTrainer.setName(trainerDto.getName());
        existingTrainer.setSpecialization(trainerDto.getSpecialization());
        existingTrainer.setBio(trainerDto.getBio());
        existingTrainer.setImageUrl(trainerDto.getImageUrl());

        Trainer updatedTrainer = trainerRepository.save(existingTrainer);
        return mapToTrainerDto(updatedTrainer);
    }

    public void deleteTrainer(UUID id) {
        if (!trainerRepository.existsById(id)) {
            throw new ResourceNotFoundException("Trainer not found with id: " + id);
        }
        trainerRepository.deleteById(id);
    }

    public List<TestimonialDto> getAllTestimonials() {
        return testimonialRepository.findAll().stream()
                .map(this::mapToTestimonialDto)
                .collect(Collectors.toList());
    }

    public TestimonialDto getTestimonialById(UUID id) {
        Testimonial testimonial = testimonialRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Testimonial not found with id: " + id));
        return mapToTestimonialDto(testimonial);
    }

    public TestimonialDto createTestimonial(TestimonialDto testimonialDto) {
        Testimonial testimonial = mapToTestimonialEntity(testimonialDto);
        testimonial.setId(null); // Ensure ID is generated by DB
        if (testimonial.getDisplayDate() == null) {
            testimonial.setDisplayDate(LocalDate.now());
        }
        Testimonial savedTestimonial = testimonialRepository.save(testimonial);
        return mapToTestimonialDto(savedTestimonial);
    }

    public TestimonialDto updateTestimonial(UUID id, TestimonialDto testimonialDto) {
        Testimonial existingTestimonial = testimonialRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Testimonial not found with id: " + id));

        existingTestimonial.setAuthorName(testimonialDto.getAuthorName());
        existingTestimonial.setRating(testimonialDto.getRating());
        existingTestimonial.setContent(testimonialDto.getContent());
        existingTestimonial.setDisplayDate(testimonialDto.getDisplayDate());

        Testimonial updatedTestimonial = testimonialRepository.save(existingTestimonial);
        return mapToTestimonialDto(updatedTestimonial);
    }

    public void deleteTestimonial(UUID id) {
        if (!testimonialRepository.existsById(id)) {
            throw new ResourceNotFoundException("Testimonial not found with id: " + id);
        }
        testimonialRepository.deleteById(id);
    }

    public TrialLeadDto createTrialLead(TrialLeadDto trialLeadDto) {
        TrialLead trialLead = mapToTrialLeadEntity(trialLeadDto);
        trialLead.setId(null); // Ensure ID is generated by DB
        trialLead.setSubmissionDate(LocalDateTime.now());
        TrialLead savedTrialLead = trialLeadRepository.save(trialLead);
        return mapToTrialLeadDto(savedTrialLead);
    }

    private TrainerDto mapToTrainerDto(Trainer trainer) {
        return TrainerDto.builder()
                .id(trainer.getId())
                .name(trainer.getName())
                .specialization(trainer.getSpecialization())
                .bio(trainer.getBio())
                .imageUrl(trainer.getImageUrl())
                .build();
    }

    private Trainer mapToTrainerEntity(TrainerDto trainerDto) {
        return new Trainer(
                trainerDto.getId(),
                trainerDto.getName(),
                trainerDto.getSpecialization(),
                trainerDto.getBio(),
                trainerDto.getImageUrl()
        );
    }

    private TestimonialDto mapToTestimonialDto(Testimonial testimonial) {
        return TestimonialDto.builder()
                .id(testimonial.getId())
                .authorName(testimonial.getAuthorName())
                .rating(testimonial.getRating())
                .content(testimonial.getContent())
                .displayDate(testimonial.getDisplayDate())
                .build();
    }

    private Testimonial mapToTestimonialEntity(TestimonialDto testimonialDto) {
        return new Testimonial(
                testimonialDto.getId(),
                testimonialDto.getAuthorName(),
                testimonialDto.getRating(),
                testimonialDto.getContent(),
                testimonialDto.getDisplayDate()
        );
    }

    private TrialLeadDto mapToTrialLeadDto(TrialLead trialLead) {
        return TrialLeadDto.builder()
                .name(trialLead.getName())
                .email(trialLead.getEmail())
                .phoneNumber(trialLead.getPhoneNumber())
                .build();
    }

    private TrialLead mapToTrialLeadEntity(TrialLeadDto trialLeadDto) {
        return new TrialLead(
                trialLeadDto.getName(),
                trialLeadDto.getEmail(),
                trialLeadDto.getPhoneNumber(),
                null // submissionDate set in service
        );
    }
}